# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0 6 * * *"
  - cron: "0 12 * * *"
  - cron: "0 18 * * *"
  - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - run: npm init -y
    - run: node index.js
